% %% plots_paper.m
% Paper-ready plotting script with a clean IEEE-style layout.
% Required workspace variables:
%   t_total, logs

close all;

if ~exist('t_total', 'var')
    error('Variable "t_total" was not found in the workspace.');
end
if ~exist('logs', 'var')
    error('Variable "logs" was not found in the workspace.');
end
if ~exist('metrics', 'var')
    error('Variable "metrics" was not found in the workspace.');
end

%% Logged signals
time_vector = t_total;

uav_x_position = logs.x;
uav_y_position = logs.y;
uav_altitude = logs.h;

reference_x_position = logs.ref_cont(:,1);
reference_y_position = logs.ref_cont(:,2);
reference_altitude = logs.ref_cont(:,3);

ground_speed = logs.Vg;
flight_path_angle_deg = rad2deg(logs.gamma);
total_lyapunov_value = logs.Vtot;
euclidean_distance = metrics.ED;

engine_thrust = logs.Th_d_zoh;
g_load = logs.ng_d_zoh;
bank_angle_deg = rad2deg(logs.phib_d_zoh);

%% Constraint values
constraint_values = uav_constraints();

%% Style setup
figure_font_name = 'Times New Roman';
axis_font_size = 10;
legend_font_size = 9;
title_font_size = 11;

main_line_width = 1.8;
reference_line_width = 1.8;
limit_line_width = 1.5;
axes_line_width = 1.1;
marker_size_value = 7;

uav_color = [0.00 0.20 0.90];
reference_color = [0.85 0.45 0.10];
limit_color = [1.00 0.20 0.20];
start_color = [0.00 0.70 0.00];
end_color = [0.90 0.00 0.00];
grid_color = [0.85 0.85 0.85];
hil_line_color = [0.00 0.10 1.00];
hil_mean_color = [0.55 0.25 0.75];
time_plot_end = 220;

transient_altitude_lower = 69.5;
transient_altitude_upper = 80.5;
transient_index_end = find(uav_altitude >= 79.8, 1, 'first');
if isempty(transient_index_end)
    transient_index_end = min(numel(time_vector), max(10, round(0.10 * numel(time_vector))));
end

reference_alignment_tolerance = 0.03;
reference_alignment_extension = find(abs(uav_altitude(transient_index_end:end) - ...
    reference_altitude(transient_index_end:end)) <= reference_alignment_tolerance, 1, 'first');
if ~isempty(reference_alignment_extension)
    transient_index_end = transient_index_end + reference_alignment_extension - 1;
end
transient_altitude_plot_end_time = 12;

transient_x_data = uav_x_position(1:transient_index_end);
transient_y_data = uav_y_position(1:transient_index_end);
transient_reference_x_data = reference_x_position(1:transient_index_end);
transient_reference_y_data = reference_y_position(1:transient_index_end);
transient_time_data = time_vector(1:transient_index_end);
transient_altitude_data = uav_altitude(1:transient_index_end);
transient_reference_altitude_data = reference_altitude(1:transient_index_end);
transient_altitude_plot_index_end = find(time_vector <= transient_altitude_plot_end_time, 1, 'last');
if isempty(transient_altitude_plot_index_end)
    transient_altitude_plot_index_end = numel(time_vector);
end
transient_altitude_time_data = time_vector(1:transient_altitude_plot_index_end);
transient_altitude_plot_data = uav_altitude(1:transient_altitude_plot_index_end);
transient_reference_altitude_plot_data = reference_altitude(1:transient_altitude_plot_index_end);
initial_zoom_time_end = transient_time_data(end);
initial_zoom_vg_lower = min(ground_speed(1:transient_index_end)) - 0.3;
initial_zoom_vg_upper = max(ground_speed(1:transient_index_end)) + 0.3;
initial_zoom_thrust_lower = min(engine_thrust(1:transient_index_end)) - 3.0;
initial_zoom_thrust_upper = max(engine_thrust(1:transient_index_end)) + 3.0;

transient_x_margin = max(5, 0.10 * max(abs(transient_x_data - mean(transient_x_data))));
transient_y_margin = max(5, 0.10 * max(abs(transient_y_data - mean(transient_y_data))));

output_directory = fullfile(fileparts(mfilename('fullpath')), 'figures_paper');
if ~exist(output_directory, 'dir')
    mkdir(output_directory);
end

hil_data_file = fullfile(fileparts(mfilename('fullpath')), 'computational_times.csv');

%% Figure 1: 3D trajectory
trajectory_3d_figure = figure('Color', 'w');
set(trajectory_3d_figure, 'Units', 'centimeters');
trajectory_3d_figure.Position(3:4) = [14 9.5];
set(trajectory_3d_figure, 'PaperPositionMode', 'auto');

uav_trajectory_handle = plot3(uav_x_position, uav_y_position, uav_altitude, ...
    '-', 'Color', uav_color, 'LineWidth', main_line_width);
hold on;
plot3(reference_x_position, reference_y_position, reference_altitude, ...
    '--', 'Color', reference_color, 'LineWidth', main_line_width);
reference_legend_handle = plot3(NaN, NaN, NaN, ...
    '-', 'Color', reference_color, 'LineWidth', main_line_width);
initial_position_handle = plot3(uav_x_position(1), uav_y_position(1), uav_altitude(1), ...
    'o', 'Color', start_color, 'MarkerFaceColor', start_color, 'MarkerSize', marker_size_value);
final_position_handle = plot3(uav_x_position(end), uav_y_position(end), uav_altitude(end), ...
    'o', 'Color', end_color, 'MarkerFaceColor', end_color, 'MarkerSize', marker_size_value);
grid off;
axis tight;
view(38, 24);
pbaspect([1 1 0.65]);
xlabel('x [m]', 'FontName', figure_font_name, 'FontSize', axis_font_size, 'FontWeight', 'bold');
ylabel('y [m]', 'FontName', figure_font_name, 'FontSize', axis_font_size, 'FontWeight', 'bold');
zlabel('h [m]', 'FontName', figure_font_name, 'FontSize', axis_font_size, 'FontWeight', 'bold');
legend([uav_trajectory_handle, reference_legend_handle, initial_position_handle, final_position_handle], ...
    {'UAV trajectory', 'Reference trajectory', 'Initial UAV position', 'Final UAV position'}, ...
    'Position', [0.62 0.33 0.23 0.14], 'FontName', figure_font_name, ...
    'FontSize', legend_font_size, 'FontWeight', 'bold', 'Box', 'on', 'NumColumns', 1);
set(gca, 'FontName', figure_font_name, ...
    'FontSize', axis_font_size, ...
    'FontWeight', 'bold', ...
    'LineWidth', axes_line_width, ...
    'GridColor', grid_color, ...
    'GridAlpha', 0.9, ...
    'Box', 'on', ...
    'Layer', 'top', ...
    'Position', [0.12 0.16 0.75 0.76]);

print(trajectory_3d_figure, fullfile(output_directory, 'fig1_3d_trajectory.eps'), ...
    '-depsc', '-painters');

%% Figure 2: Euclidean distance evolution
euclidean_distance_figure = figure('Color', 'w');
set(euclidean_distance_figure, 'Units', 'centimeters');
euclidean_distance_figure.Position(3:4) = [12 5];
set(euclidean_distance_figure, 'PaperPositionMode', 'auto');

plot(time_vector, euclidean_distance, ...
    'Color', uav_color, 'LineWidth', main_line_width);
grid off;
xlim([0, time_plot_end]);
xlabel('Time [s]', 'FontName', figure_font_name, 'FontSize', axis_font_size, 'FontWeight', 'bold');
ylabel('Euclidean distance [m]', 'FontName', figure_font_name, 'FontSize', axis_font_size, 'FontWeight', 'bold');
set(gca, 'FontName', figure_font_name, ...
    'FontSize', axis_font_size, ...
    'FontWeight', 'bold', ...
    'LineWidth', axes_line_width, ...
    'GridColor', grid_color, ...
    'GridAlpha', 0.9, ...
    'Box', 'on', ...
    'Layer', 'top');

print(euclidean_distance_figure, fullfile(output_directory, 'fig2_euclidean_distance.eps'), ...
    '-depsc', '-painters');

%% Figure 3: Input constraints
input_constraint_figure = figure('Color', 'w');
set(input_constraint_figure, 'Units', 'centimeters');
input_constraint_figure.Position(3:4) = [12 13.5];
set(input_constraint_figure, 'PaperPositionMode', 'auto');
thrust_axis = subplot(3, 1, 1, 'Parent', input_constraint_figure);
set(thrust_axis, 'Position', [0.11 0.71 0.83 0.17]);
plot(thrust_axis, time_vector, engine_thrust, ...
    'Color', uav_color, 'LineWidth', main_line_width);
hold(thrust_axis, 'on');
yline(thrust_axis, constraint_values.Th_min, '--', ...
    'Color', limit_color, 'LineWidth', limit_line_width);
yline(thrust_axis, constraint_values.Th_max, '--', ...
    'Color', limit_color, 'LineWidth', limit_line_width);
grid(thrust_axis, 'off');
ylabel(thrust_axis, 'T_h [N]', 'FontName', figure_font_name, ...
    'FontSize', axis_font_size, 'FontWeight', 'bold');
xlim(thrust_axis, [0, time_plot_end]);
ylim(thrust_axis, [-10, 130]);
yticks(thrust_axis, [constraint_values.Th_min 20 60 constraint_values.Th_max]);
yticklabels(thrust_axis, {'1', '20', '60', '120'});
legend(thrust_axis, {'$T_h$', 'Constraints'}, ...
    'Location', 'east', 'FontName', figure_font_name, ...
    'FontSize', legend_font_size, 'FontWeight', 'bold', 'Box', 'on', 'Interpreter', 'latex', 'NumColumns', 1);
set(thrust_axis, 'FontName', figure_font_name, ...
    'FontSize', axis_font_size, ...
    'FontWeight', 'bold', ...
    'LineWidth', axes_line_width, ...
    'GridColor', grid_color, ...
    'GridAlpha', 0.9, ...
    'Box', 'on', ...
    'Layer', 'top');

thrust_axis_position = get(thrust_axis, 'Position');
thrust_zoom_axis = axes('Position', [ ...
    thrust_axis_position(1) + 0.26 * thrust_axis_position(3), ...
    thrust_axis_position(2) + 0.36 * thrust_axis_position(4), ...
    0.25 * thrust_axis_position(3), ...
    0.32 * thrust_axis_position(4)]);
plot(thrust_zoom_axis, transient_time_data, engine_thrust(1:transient_index_end), ...
    'Color', uav_color, 'LineWidth', 1.2);
hold(thrust_zoom_axis, 'on');
yline(thrust_zoom_axis, constraint_values.Th_min, '--', ...
    'Color', limit_color, 'LineWidth', 1.0);
yline(thrust_zoom_axis, constraint_values.Th_max, '--', ...
    'Color', limit_color, 'LineWidth', 1.0);
grid(thrust_zoom_axis, 'off');
xlim(thrust_zoom_axis, [0, 2.5]);
ylim(thrust_zoom_axis, [10, 140]);
yticks(thrust_zoom_axis, [20 60 constraint_values.Th_max]);
set(thrust_zoom_axis, 'FontName', figure_font_name, ...
    'FontSize', 7, ...
    'FontWeight', 'bold', ...
    'LineWidth', 0.8, ...
    'GridColor', grid_color, ...
    'GridAlpha', 0.9, ...
    'Box', 'on', ...
    'Layer', 'top');
title(thrust_zoom_axis, 'Zoom', 'FontName', figure_font_name, ...
    'FontSize', 7, 'FontWeight', 'bold');

g_load_axis = subplot(3, 1, 2, 'Parent', input_constraint_figure);
set(g_load_axis, 'Position', [0.11 0.43 0.83 0.17]);
plot(g_load_axis, time_vector, g_load, ...
    'Color', uav_color, 'LineWidth', main_line_width);
hold(g_load_axis, 'on');
yline(g_load_axis, constraint_values.ng_min, '--', ...
    'Color', limit_color, 'LineWidth', limit_line_width);
yline(g_load_axis, constraint_values.ng_max, '--', ...
    'Color', limit_color, 'LineWidth', limit_line_width);
grid(g_load_axis, 'off');
ylabel(g_load_axis, 'n_g [G]', 'FontName', figure_font_name, ...
    'FontSize', axis_font_size, 'FontWeight', 'bold');
xlim(g_load_axis, [0, time_plot_end]);
ylim(g_load_axis, [-0.5, 2.6]);
yticks(g_load_axis, [constraint_values.ng_min 1 constraint_values.ng_max]);
legend(g_load_axis, {'$n_g$', 'Constraints'}, ...
    'Location', 'southeast', 'FontName', figure_font_name, ...
    'FontSize', legend_font_size, 'FontWeight', 'bold', 'Box', 'on', 'Interpreter', 'latex', 'NumColumns', 2);
set(g_load_axis, 'FontName', figure_font_name, ...
    'FontSize', axis_font_size, ...
    'FontWeight', 'bold', ...
    'LineWidth', axes_line_width, ...
    'GridColor', grid_color, ...
    'GridAlpha', 0.9, ...
    'Box', 'on', ...
    'Layer', 'top');

bank_angle_axis = subplot(3, 1, 3, 'Parent', input_constraint_figure);
set(bank_angle_axis, 'Position', [0.11 0.18 0.83 0.16]);
plot(bank_angle_axis, time_vector, bank_angle_deg, ...
    'Color', uav_color, 'LineWidth', main_line_width);
hold(bank_angle_axis, 'on');
yline(bank_angle_axis, rad2deg(constraint_values.phib_min), '--', ...
    'Color', limit_color, 'LineWidth', limit_line_width);
yline(bank_angle_axis, rad2deg(constraint_values.phib_max), '--', ...
    'Color', limit_color, 'LineWidth', limit_line_width);
grid(bank_angle_axis, 'off');
xlim(bank_angle_axis, [0, time_plot_end]);
ylim(bank_angle_axis, [-40, 40]);
yticks(bank_angle_axis, [rad2deg(constraint_values.phib_min) 0 rad2deg(constraint_values.phib_max)]);
xlabel(bank_angle_axis, 'Time [s]', 'FontName', figure_font_name, ...
    'FontSize', axis_font_size, 'FontWeight', 'bold');
ylabel(bank_angle_axis, '\phi_b [deg]', 'FontName', figure_font_name, ...
    'FontSize', axis_font_size, 'FontWeight', 'bold');
legend(bank_angle_axis, {'$\phi_b$', 'Constraints'}, ...
    'Location', 'southeast', 'FontName', figure_font_name, ...
    'FontSize', legend_font_size, 'FontWeight', 'bold', 'Box', 'on', 'Interpreter', 'latex', 'NumColumns', 2);
set(bank_angle_axis, 'FontName', figure_font_name, ...
    'FontSize', axis_font_size, ...
    'FontWeight', 'bold', ...
    'LineWidth', axes_line_width, ...
    'GridColor', grid_color, ...
    'GridAlpha', 0.9, ...
    'Box', 'on', ...
    'Layer', 'top');
text(thrust_axis, 0.5, -0.36, '(a)', 'Units', 'normalized', ...
    'HorizontalAlignment', 'center', 'FontName', figure_font_name, ...
    'FontSize', axis_font_size, 'FontWeight', 'bold');
text(g_load_axis, 0.5, -0.36, '(b)', 'Units', 'normalized', ...
    'HorizontalAlignment', 'center', 'FontName', figure_font_name, ...
    'FontSize', axis_font_size, 'FontWeight', 'bold');
text(bank_angle_axis, 0.5, -0.24, '(c)', 'Units', 'normalized', ...
    'HorizontalAlignment', 'center', 'FontName', figure_font_name, ...
    'FontSize', axis_font_size, 'FontWeight', 'bold');
bank_angle_xlabel_handle = get(bank_angle_axis, 'XLabel');
set(bank_angle_xlabel_handle, 'Units', 'normalized');
set(bank_angle_xlabel_handle, 'Position', [0.5 -0.44 0]);

print(input_constraint_figure, fullfile(output_directory, 'fig3_input_constraints.eps'), ...
    '-depsc', '-painters');

%% Figure 4: State constraints
state_constraint_figure = figure('Color', 'w');
set(state_constraint_figure, 'Units', 'centimeters');
state_constraint_figure.Position(3:4) = [12 10];
set(state_constraint_figure, 'PaperPositionMode', 'auto');
ground_speed_axis = subplot(2, 1, 1, 'Parent', state_constraint_figure);
plot(ground_speed_axis, time_vector, ground_speed, ...
    'Color', uav_color, 'LineWidth', main_line_width);
hold(ground_speed_axis, 'on');
yline(ground_speed_axis, constraint_values.Vg_min, '--', ...
    'Color', limit_color, 'LineWidth', limit_line_width);
yline(ground_speed_axis, constraint_values.Vg_max, '--', ...
    'Color', limit_color, 'LineWidth', limit_line_width);
grid(ground_speed_axis, 'off');
ylabel(ground_speed_axis, 'V_g [m/s]', 'FontName', figure_font_name, ...
    'FontSize', axis_font_size, 'FontWeight', 'bold');
xlim(ground_speed_axis, [0, time_plot_end]);
ylim(ground_speed_axis, [23, 36.0]);
yticks(ground_speed_axis, [constraint_values.Vg_min 27 32 constraint_values.Vg_max]);
legend(ground_speed_axis, {'$V_g$', 'Constraints'}, ...
    'Position', [0.46 0.84 0.32 0.05], 'FontName', figure_font_name, ...
    'FontSize', legend_font_size, 'FontWeight', 'bold', 'Box', 'on', 'Interpreter', 'latex', 'NumColumns', 2);
set(ground_speed_axis, 'FontName', figure_font_name, ...
    'FontSize', axis_font_size, ...
    'FontWeight', 'bold', ...
    'LineWidth', axes_line_width, ...
    'GridColor', grid_color, ...
    'GridAlpha', 0.9, ...
    'Box', 'on', ...
    'Layer', 'top');

ground_speed_axis_position = get(ground_speed_axis, 'Position');
ground_speed_zoom_axis = axes('Position', [ ...
    ground_speed_axis_position(1) + 0.22 * ground_speed_axis_position(3), ...
    ground_speed_axis_position(2) + 0.24 * ground_speed_axis_position(4), ...
    0.28 * ground_speed_axis_position(3), ...
    0.34 * ground_speed_axis_position(4)]);
plot(ground_speed_zoom_axis, transient_time_data, ground_speed(1:transient_index_end), ...
    'Color', uav_color, 'LineWidth', 1.2);
hold(ground_speed_zoom_axis, 'on');
yline(ground_speed_zoom_axis, constraint_values.Vg_min, '--', ...
    'Color', limit_color, 'LineWidth', 1.0);
yline(ground_speed_zoom_axis, constraint_values.Vg_max, '--', ...
    'Color', limit_color, 'LineWidth', 1.0);
grid(ground_speed_zoom_axis, 'off');
xlim(ground_speed_zoom_axis, [transient_time_data(1), initial_zoom_time_end]);
ylim(ground_speed_zoom_axis, [33, 37]);
yticks(ground_speed_zoom_axis, [33 35 37]);
set(ground_speed_zoom_axis, 'FontName', figure_font_name, ...
    'FontSize', 7, ...
    'FontWeight', 'bold', ...
    'LineWidth', 0.8, ...
    'GridColor', grid_color, ...
    'GridAlpha', 0.9, ...
    'Box', 'on', ...
    'Layer', 'top');
title(ground_speed_zoom_axis, 'Zoom', 'FontName', figure_font_name, ...
    'FontSize', 7, 'FontWeight', 'bold');

flight_path_axis = subplot(2, 1, 2, 'Parent', state_constraint_figure);
set(flight_path_axis, 'Position', [0.13 0.19 0.78 0.23]);
plot(flight_path_axis, time_vector, flight_path_angle_deg, ...
    'Color', uav_color, 'LineWidth', main_line_width);
hold(flight_path_axis, 'on');
yline(flight_path_axis, rad2deg(constraint_values.gamma_min), '--', ...
    'Color', limit_color, 'LineWidth', limit_line_width);
yline(flight_path_axis, rad2deg(constraint_values.gamma_max), '--', ...
    'Color', limit_color, 'LineWidth', limit_line_width);
grid(flight_path_axis, 'off');
xlim(flight_path_axis, [0, time_plot_end]);
ylim(flight_path_axis, [-12, 17]);
yticks(flight_path_axis, [rad2deg(constraint_values.gamma_min) 0 rad2deg(constraint_values.gamma_max)]);
xlabel(flight_path_axis, 'Time [s]', 'FontName', figure_font_name, ...
    'FontSize', axis_font_size, 'FontWeight', 'bold');
ylabel(flight_path_axis, '\gamma [deg]', 'FontName', figure_font_name, ...
    'FontSize', axis_font_size, 'FontWeight', 'bold');
legend(flight_path_axis, {'$\gamma$', 'Constraints'}, ...
    'Position', [0.64 0.32 0.16 0.05], 'FontName', figure_font_name, ...
    'FontSize', legend_font_size, 'FontWeight', 'bold', 'Box', 'on', 'Interpreter', 'latex', 'NumColumns', 1);
set(flight_path_axis, 'FontName', figure_font_name, ...
    'FontSize', axis_font_size, ...
    'FontWeight', 'bold', ...
    'LineWidth', axes_line_width, ...
    'GridColor', grid_color, ...
    'GridAlpha', 0.9, ...
    'Box', 'on', ...
    'Layer', 'top');
text(ground_speed_axis, 0.5, -0.28, '(a)', 'Units', 'normalized', ...
    'HorizontalAlignment', 'center', 'FontName', figure_font_name, ...
    'FontSize', axis_font_size, 'FontWeight', 'bold', 'Clipping', 'off');
text(flight_path_axis, 0.5, -0.30, '(b)', 'Units', 'normalized', ...
    'HorizontalAlignment', 'center', 'FontName', figure_font_name, ...
    'FontSize', axis_font_size, 'FontWeight', 'bold', 'Clipping', 'off');
flight_path_xlabel_handle = get(flight_path_axis, 'XLabel');
set(flight_path_xlabel_handle, 'Units', 'normalized');
set(flight_path_xlabel_handle, 'Position', [0.5 -0.42 0]);

print(state_constraint_figure, fullfile(output_directory, 'fig4_state_constraints.eps'), ...
    '-depsc', '-painters');

%% Figure 5: Total Lyapunov function
lyapunov_figure = figure('Color', 'w');
set(lyapunov_figure, 'Units', 'centimeters');
lyapunov_figure.Position(3:4) = [12 5];
set(lyapunov_figure, 'PaperPositionMode', 'auto');

plot(time_vector, total_lyapunov_value, ...
    'Color', uav_color, 'LineWidth', main_line_width);
grid off;
xlim([0, time_plot_end]);
ylim([0, 550]);
yticks([0 500]);
xlabel('Time [s]', 'FontName', figure_font_name, 'FontSize', axis_font_size, 'FontWeight', 'bold');
ylabel('V(e_k)', 'FontName', figure_font_name, 'FontSize', axis_font_size, 'FontWeight', 'bold');
title(' ', 'FontSize', title_font_size);
set(gca, 'FontName', figure_font_name, ...
    'FontSize', axis_font_size, ...
    'FontWeight', 'bold', ...
    'LineWidth', axes_line_width, ...
    'GridColor', grid_color, ...
    'GridAlpha', 0.9, ...
    'Box', 'on', ...
    'Layer', 'top');

print(lyapunov_figure, fullfile(output_directory, 'fig5_lyapunov_Vek.eps'), ...
    '-depsc', '-painters');

%% Figure 6: HIL computational time
if exist(hil_data_file, 'file')
    hil_computational_time_ms = readmatrix(hil_data_file);
    hil_computational_time_ms = hil_computational_time_ms(:);
    hil_index_end = min(2200, numel(hil_computational_time_ms));
    hil_computational_time_ms = hil_computational_time_ms(1:hil_index_end);
    hil_step_index = 1:numel(hil_computational_time_ms);
    hil_mean_time_ms = mean(hil_computational_time_ms);

    hil_figure = figure('Color', 'w');
    set(hil_figure, 'Units', 'centimeters');
    hil_figure.Position(3:4) = [13 7.5];
    set(hil_figure, 'PaperPositionMode', 'auto');

    plot(hil_step_index, hil_computational_time_ms, ...
        'Color', hil_line_color, 'LineWidth', main_line_width);
    hold on;
    yline(hil_mean_time_ms, '--', 'Color', hil_mean_color, ...
        'LineWidth', reference_line_width);
    grid off;
    xlim([0 2200]);
    xticks([0 500 1000 1500 2000 2200]);
    xlabel('k', 'FontName', figure_font_name, 'FontSize', axis_font_size, 'FontWeight', 'bold');
    ylabel('Computational time [ms]', 'FontName', figure_font_name, 'FontSize', axis_font_size, 'FontWeight', 'bold');
    legend({'HIL computational time', 'Mean computational time'}, ...
        'Location', 'northeast', 'FontName', figure_font_name, ...
        'FontSize', 8, 'FontWeight', 'bold', 'Box', 'on', 'NumColumns', 2);
    set(gca, 'FontName', figure_font_name, ...
        'FontSize', axis_font_size, ...
        'FontWeight', 'bold', ...
        'LineWidth', axes_line_width, ...
        'GridColor', grid_color, ...
        'GridAlpha', 0.9, ...
        'Box', 'on', ...
        'Layer', 'top');

print(hil_figure, fullfile(output_directory, 'fig6_hil_computational_time.eps'), ...
        '-depsc', '-painters');
else
    warning('File "%s" was not found. Skipping HIL computational time figure.', hil_data_file);
end

fprintf('Selected paper figures were saved in:\n%s\n', output_directory);
